# Generated by Django 3.1.7 on 2022-01-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('newsid', models.IntegerField()),
                ('comments', models.CharField(max_length=1000)),
                ('userid', models.IntegerField()),
                ('touserid', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='givelike',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField()),
                ('newsid', models.IntegerField()),
                ('givelikeornot', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='history',
            fields=[
                ('userid', models.IntegerField()),
                ('history_newsid', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='hotword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotword', models.CharField(max_length=50)),
                ('num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField()),
                ('message', models.CharField(max_length=1000)),
                ('time', models.CharField(max_length=30)),
                ('newsid', models.IntegerField()),
                ('hadread', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='newsdetail',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=30)),
                ('pic_url', models.CharField(max_length=1000)),
                ('videourl', models.CharField(max_length=200)),
                ('mainpage', models.CharField(max_length=2000)),
                ('origin', models.CharField(max_length=2000)),
                ('category', models.IntegerField()),
                ('readnum', models.IntegerField()),
                ('comments', models.IntegerField()),
                ('keywords', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='newshot',
            fields=[
                ('news_id', models.IntegerField(primary_key=True, serialize=False)),
                ('news_hot', models.FloatField()),
                ('category', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='newssimilar',
            fields=[
                ('new_id_base', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('new_id_sim', models.CharField(max_length=64)),
                ('new_correlation', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='recommend',
            fields=[
                ('userid', models.IntegerField(primary_key=True, serialize=False)),
                ('newsid', models.IntegerField()),
                ('hadread', models.IntegerField()),
                ('cor', models.FloatField()),
                ('species', models.IntegerField()),
                ('time', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='spiderstate',
            fields=[
                ('spiderid', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.IntegerField()),
                ('interval', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='urlcollect',
            fields=[
                ('url', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('handle', models.IntegerField()),
                ('type', models.IntegerField()),
                ('time', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('userid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=50)),
                ('gender', models.IntegerField()),
                ('ip', models.GenericIPAddressField()),
                ('password', models.CharField(max_length=20)),
                ('tags', models.CharField(max_length=2000)),
                ('tagsweight', models.CharField(max_length=2000)),
                ('headPortrait', models.CharField(max_length=255)),
            ],
        ),
    ]
